version: "3"

services:
  flaskapi:
    build:
      context: .
      dockerfile: api/Dockerfile
      args:
        SOURCE_DIR: "./api"
    environment:
      FLASK_ENV: development
    ports: #[HOST_PORT:CONTAINER_PORT]
      - 8000:5000
    volumes:
      - ./api:/app # [Host volume]
    expose:
      - 8000

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        SOURCE_DIR: "./frontend"
    ports:
      - "8080:80"
    volumes:
      # - ./frontend/nginx:/etc/nginx/conf.d
      - ./frontend/src:/usr/share/nginx/html
    restart: always
    depends_on:
      - flaskapi

  #   depends_on:
  #     - redis
  # redis:
  #   image: redis:alpine

  # nginx:
  #   image: nginx
  #   volumes:
  #     - ./nginx:/etc/nginx/conf.d
  #     - ./front-end:/var/www/front-end
  #   ports:
  #     - "80:80"
